sonar.projectKey=Kiioskii_E-biznes-fornt
sonar.organization=kiioskii

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,build/**,**/*.test.jsx,**/*.test.js,src/test/**
sonar.coverage.exclusions=src/main.jsx,src/styles.css

sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js,src/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info